---
title: "Visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
cases <- read.csv(file = 'Output_Data/case_clean.csv')
hosp <- read.csv(file = "Output_data/hosp_clean.csv")
icu <- read.csv(file = "Output_data/icu_clean.csv")
daily_death <- read.csv(file = "Output_data/daily_death.csv")

VIC <- cases$VIC
NSW <- cases$NSW
```

```{r}
VIC_chain <- readRDS("Output_Data/chain.RData")
NSW_chain <- readRDS("Output_Data/chain_1.RData")
```

# Posterior Distributions
```{r}
burnIn = 500
num_iter = 100000
png(filename="Plots/Posterior Distributions.png")
par(mfrow=c(3,2))
hist(VIC_chain[-(1:burnIn), 1], main="Posterior of P(Hospital|Cases)", xlab="P_H", freq = FALSE)
hist(VIC_chain[-(1:burnIn), 2], main="Posterior of P(ICU|Hospital)", xlab="P_ICU", freq = FALSE)
hist(VIC_chain[-(1:burnIn), 3], main="Posterior of P(Death|General Ward)", xlab="P_H_D", freq = FALSE)
hist(VIC_chain[-(1:burnIn), 4], main="Posterior of P(Death|ICU)", xlab="P_ICU_D", freq = FALSE)
hist(VIC_chain[-(1:burnIn), 5], main="Posterior of P(Death|Post-ICU)", xlab="P_W_D", freq = FALSE)
dev.off()
```

# Random Sampling from the chain
```{r}
sample_num = 1000
random_sample_VIC = VIC_chain[sample(1:num_iter, sample_num),]
```


```{r}
sample_num = 1000
random_sample_NSW = NSW_chain[sample(1:num_iter, sample_num),]
```


# Extract the quantiles for the simulations
```{r}
getQuantile <- function(input, sample, sample_num){
  hosp_simulation_list = as.list(rep(NA, sample_num))
  icu_simulation_list = as.list(rep(NA, sample_num))
  death_simulation_list = as.list(rep(NA, sample_num))

  for(i in 1:sample_num){
    Ph = sample[i,][1]
    PICUpre = sample[i,][2]
    Phd = sample[i,][3]
    PICUd = sample[i,][4]
    PICUpd = sample[i,][5]
  
    simulation_w = ward_simulation(input, Ph, PICUpre, Phd)
    simulation_i = icu_simulation(input, Ph, PICUpre, PICUd, PICUpd)
  
    hosp_simu = simulation_w[[1]] + simulation_i[[1]] + simulation_i[[2]] + simulation_i[[3]]
    icu_simu = simulation_i[[1]]
    death_simu = simulation_w[[2]] + simulation_i[[4]] + simulation_i[[5]]
  
    hosp_simulation_list[[i]] = hosp_simu
    icu_simulation_list[[i]] = icu_simu
    death_simulation_list[[i]] = death_simu
  }
  
  h_simu = hosp_simulation_list[[1]]
  i_simu = icu_simulation_list[[1]]
  d_simu = death_simulation_list[[1]]

  for(i in 2:sample_num){
    h_simu = cbind(h_simu, hosp_simulation_list[[i]])
    i_simu = cbind(i_simu, icu_simulation_list[[i]])
    d_simu = cbind(d_simu, death_simulation_list[[i]])
  }
  
  h_simu_median = replicate(length(input), 0)
  h_simu_5_quan = replicate(length(input), 0)
  h_simu_95_quan = replicate(length(input), 0)
  i_simu_median = replicate(length(input), 0)
  i_simu_5_quan = replicate(length(input), 0)
  i_simu_95_quan = replicate(length(input), 0)
  d_simu_median = replicate(length(input), 0)
  d_simu_5_quan = replicate(length(input), 0)
  d_simu_95_quan = replicate(length(input), 0)

  for(i in 1:length(input)){
  
    h_simu_median[i] = median(h_simu[i,])
    h_simu_5_quan[i] = quantile(h_simu[i,],probs=0.05)
    h_simu_95_quan[i] = quantile(h_simu[i,],probs=0.95)
  
    i_simu_median[i] = median(i_simu[i,])
    i_simu_5_quan[i] = quantile(i_simu[i,],probs=0.05)
    i_simu_95_quan[i] = quantile(i_simu[i,],probs=0.95)
  
    d_simu_median[i] = median(d_simu[i,])
    d_simu_5_quan[i] = quantile(d_simu[i,],probs=0.05)
    d_simu_95_quan[i] = quantile(d_simu[i,],probs=0.95)
  }
  
  return(list(h_simu_median, h_simu_5_quan, h_simu_95_quan, 
              i_simu_median, i_simu_5_quan, i_simu_95_quan, 
              d_simu_median, d_simu_5_quan, d_simu_95_quan))
}
```


```{r}
start_time <- Sys.time()

VIC_simu <- getQuantile(VIC, random_sample_VIC, sample_num)

end_time <- Sys.time()
print(end_time - start_time)
```

```{r}
start_time <- Sys.time()

NSW_simu <- getQuantile(NSW, random_sample_NSW, sample_num)

end_time <- Sys.time()
print(end_time - start_time)
```

# Visualization
```{r}
library(ggplot2)
```

```{r}
hosp$Date = as.Date(hosp$Date, format = c("%m-%d"))

VIC_hosp_simulation <- data.frame(
  date = hosp$Date,
  sim = VIC_simu[[1]]
)

VIC_hosp_occupancy <- ggplot(VIC_hosp_simulation, aes(x = date, y = sim, color="simulation")) + 
  geom_ribbon(aes(ymin=VIC_simu[[2]], ymax=VIC_simu[[3]]), alpha=0.2) + 
  geom_line(data = hosp, aes(x = Date, y = VIC, color="data")) +
  scale_colour_manual("", 
                      breaks = c("simulation", "data"),
                      values = c("blue", "black")) +
  labs(x = "Date (Year: 2021)", title = "Hospital Occupancy Simulation in VIC") +
  theme(plot.title = element_text(size=11)) +
  scale_y_continuous("Hospital Occupancy", limits = c(0,1000))
VIC_hosp_occupancy
```

```{r}
icu$Date = as.Date(icu$Date, format = c("%m-%d"))

VIC_icu_simulation <- data.frame(
  date = icu$Date,
  sim = VIC_simu[[4]]
)

VIC_icu_occupancy <- ggplot(VIC_icu_simulation, aes(x = date, y = sim, color="simulation")) + 
  geom_ribbon(aes(ymin=VIC_simu[[5]], ymax=VIC_simu[[6]]), alpha=0.2) + 
  geom_line(data = icu, aes(x = Date, y = VIC, color="data")) +
  scale_colour_manual("", 
                      breaks = c("simulation", "data"),
                      values = c("blue", "black")) +
  labs(x = "Date (Year: 2021)", title = "ICU Occupancy Simulation in VIC") +
  theme(plot.title = element_text(size=11)) +
  scale_y_continuous("ICU Occupancy", limits = c(0,220))
VIC_icu_occupancy
```

```{r}
daily_death$Date = as.Date(daily_death$Date, format = c("%m-%d"))

death_simulation_VIC <- data.frame(
  date = daily_death$Date,
  sim = VIC_simu[[7]]
)

VIC_daily_death_plot <- ggplot(data = death_simulation_VIC, aes(x = date, y = sim, color="simulation")) + 
  geom_ribbon(aes(ymin=VIC_simu[[8]], ymax=VIC_simu[[9]]), alpha=0.2) +
  geom_line(data = daily_death, aes(x = Date, y = VIC, color="data")) +
  scale_colour_manual("", 
                      breaks = c("simulation", "data"),
                      values = c("blue", "black")) +
  labs(x = "Date (Year: 2021)", title = "Daily Death Simulation in VIC") +
  theme(plot.title = element_text(size=11)) +
  scale_y_continuous("Daily Deaths", limits = c(0,35))
VIC_daily_death_plot
```



```{r}
hosp$Date = as.Date(hosp$Date, format = c("%m-%d"))

NSW_hosp_simulation <- data.frame(
  date = hosp$Date,
  sim = NSW_simu[[1]]
)

NSW_hosp_occupancy <- ggplot(NSW_hosp_simulation, aes(x = date, y = sim, color="simulation")) + 
  geom_ribbon(aes(ymin=NSW_simu[[2]], ymax=NSW_simu[[3]]), alpha=0.2) + 
  geom_line(data = hosp, aes(x = Date, y = NSW, color="data")) +
  scale_colour_manual("", 
                      breaks = c("simulation", "data"),
                      values = c("blue", "black")) +
  labs(x = "Date (Year: 2021)", title = "Hospital Occupancy Simulation in NSW") +
  theme(plot.title = element_text(size=11)) +
  scale_y_continuous("Hospital Occupancy", limits = c(0,1400))
NSW_hosp_occupancy
```


```{r}
icu$Date = as.Date(icu$Date, format = c("%m-%d"))

NSW_icu_simulation <- data.frame(
  date = icu$Date,
  sim = NSW_simu[[4]]
)

NSW_icu_occupancy <- ggplot(NSW_icu_simulation, aes(x = date, y = sim, color="simulation")) + 
  geom_ribbon(aes(ymin=NSW_simu[[5]], ymax=NSW_simu[[6]]), alpha=0.2) + 
  geom_line(data = icu, aes(x = Date, y = NSW, color="data")) +
  scale_colour_manual("", 
                      breaks = c("simulation", "data"),
                      values = c("blue", "black")) +
  labs(x = "Date (Year: 2021)", title = "ICU Occupancy Simulation in NSW") +
  theme(plot.title = element_text(size=11)) +
  scale_y_continuous("ICU Occupancy", limits = c(0,320))
NSW_icu_occupancy
```


```{r}
daily_death$Date = as.Date(daily_death$Date, format = c("%m-%d"))

death_simulation_NSW <- data.frame(
  date = daily_death$Date,
  sim = NSW_simu[[7]]
)

NSW_daily_death_plot <- ggplot(data = death_simulation_NSW, aes(x = date, y = sim, color="simulation")) + 
  geom_ribbon(aes(ymin=NSW_simu[[8]], ymax=NSW_simu[[9]]), alpha=0.2) +
  geom_line(data = daily_death, aes(x = Date, y = NSW, color="data")) +
  scale_colour_manual("", 
                      breaks = c("simulation", "data"),
                      values = c("blue", "black")) +
  labs(x = "Date (Year: 2021)", title = "Daily Death Simulation in NSW") +
  theme(plot.title = element_text(size=11)) +
  scale_y_continuous("Daily Deaths", limits = c(0,25))
NSW_daily_death_plot
```

```{r}
library(ggpubr)
ggarrange(VIC_hosp_occupancy,NSW_hosp_occupancy, 
          VIC_icu_occupancy, NSW_icu_occupancy, 
          VIC_daily_death_plot, NSW_daily_death_plot, 
          ncol = 2, nrow = 3) 
ggsave("Plots/Simulation after inference.png")
```
